//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ddvplayer.rc
//
#define IDS_PROJNAME                    100
#define IDC_CHECK_LAYERS_OFF            100
#define IDC_CHECK_LAYERS_FROZEN         101
#define IDD_DIALOG_SETTINGS             102
#define IDC_CHECK_LAYERS_LOCKED         102
#define IDC_CHECK_LAYERS_FROZEN_VP      103
#define IDC_CHECK_LAYERS_FROZEN_NEW_VP  104
#define IDD_DIALOG_DDVPLAYER            104
#define IDC_BUTTON_UNREGISTER           105
#define IDC_BUTTON_REGISTER             105
#define IDC_BUTTON1                     106
#define IDC_BUTTON_ENABLED              106
#define IDC_BUTTON_GC_LAYERS_PICK_ENTITIES 106
#define IDC_LIST_GC_LAYERS              107
#define IDC_BUTTON_GC_LAYERS_SELECTALL  108
#define IDC_BUTTON_GC_LAYERS_REMOVEALL  109
#define IDC_CHECK_GC_LAYERS_OFF         110
#define IDC_CHECK_GC_LAYERS_LOCKED      111
#define IDC_CHECK_GC_LAYERS_VP_FROZEN   112
#define IDC_CHECK_GC_LAYERS_FROZEN      113
#define IDC_CHECK_GC_LAYERS_NVP_FROZEN  114
#define IDC_LIST_GC_GROUPS              115
#define IDC_BUTTON_GC_LAYERS_NEW        116
#define IDC_BUTTON_GC_LAYERS_DELETE     117
#define IDC_BUTTON_GC_LAYERS_RENAME     118
#define IDC_BUTTON_GC_LAYERS_APPLY_LAYERTABLE 119
#define IDC_BUTTON_GC_LAYERS_APPLY_VIEWPORT 120
#define IDC_BUTTON_GC_LAYERS_ONESTEP    121
#define IDC_STATIC_GC_LAYERS_FRAME      122
#define IDC_STATIC_GC_GROUPS_FRAME      123
#define IDC_BUTTON_GC_LAYERS_UPDATE     124
#define IDC_BUTTON_GC_LAYERS_LOAD       125
#define IDC_BUTTON9                     126
#define IDC_BUTTON_GC_LAYERS_SAVE       126
#define IDC_BUTTON_GC_LAYERS_NONE       127

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        106
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         124
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
